[build]
  # Build command (not needed for static site)
  command = "echo 'No build required for static site'"
  
  # Directory with the deployable files
  publish = "."
  
  # Environment variables for build process
  [build.environment]
    NODE_VERSION = "18"

# Redirects and rewrites
[[redirects]]
  # SPA fallback - redirect all non-file requests to index.html
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = { Role = ["admin"] }

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    
    # Cache control for HTML files
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Form handling (if needed in the future)
[forms]
  settings = true

# Plugin configuration
[[plugins]]
  package = "netlify-plugin-minify-html"
  [plugins.inputs]
    contexts = ['production']

# Environment-specific settings
[context.production]
  command = "echo 'Production deployment'"
  [context.production.environment]
    NODE_ENV = "production"

[context.deploy-preview]
  command = "echo 'Deploy preview'"
  [context.deploy-preview.environment]
    NODE_ENV = "staging"

[context.branch-deploy]
  command = "echo 'Branch deployment'"
  [context.branch-deploy.environment]
    NODE_ENV = "development" 